#!/bin/python
from PIL import Image
import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("name", help="Prefix of generated variables")
    parser.add_argument("input", help="The path to the png")
    parser.add_argument("output", help="The path to the header")
    args = parser.parse_args()

    image = Image.open(args.input)
    image = image.convert("RGBA")
    pd = image.load()
    byte_array = []

    width, height = image.size

    for y in range(0, height):
        for x in range(0, width):
            r, g, b, a = pd[x, y]
            byte_array.append(b)
            byte_array.append(g)
            byte_array.append(r)
            byte_array.append(a)

    image.close()

    with open(args.output, "w") as file:
        file.write("// generated by: png2h\n")

        file.write("size_t {}_image_width = {};\n".format(args.name, width))
        file.write("size_t {}_image_height = {};\n\n".format(args.name, height))

        file.write("const unsigned char {}_image_data[] = {{\n\t".format(args.name))

        index = 0
        for item in byte_array:
            file.write("{},".format(hex(item)))
            file.write("\n\t" if index % 16 == 15 else " ")
            index += 1

        file.write("};\n")

if __name__ == '__main__':
    main()
